Models/AppSetting.cs
using System;

namespace RestaurantPortfolio.Models.Entities;

public class AppSetting
{
    public int Id {get;set;}
	public string? BrandName {get;set;}
	public string? HeroTitle {get;set;}
	public string? HeroText {get;set;}
	public string? HeroImageUrl {get;set;}
	public string? AddressText {get;set;}
	public string? AddressDistrict {get;set;}
	public string? AddressProvince {get;set;}
	public string? PhoneNumber {get;set;}
	public string? Email {get;set;}
	public string? AboutSubtitle {get;set;}
	public string? AboutText {get;set;}
	public string? MenuText {get;set;}
	public DateTime CreatedDate {get;set;}
	public DateTime UpdatedDate {get;set;}

}

Areas/Admin/Controllers/AppSettingController.cs
using System.Data;
using AspNetCoreHero.ToastNotification.Abstractions;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using RestaurantPortfolio.Areas.Admin.Entities.Repositories;
using RestaurantPortfolio.Areas.Admin.ViewModels;
using RestaurantPortfolio.Helpers;

namespace RestaurantPortfolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AppSettingController : Controller
    {
        private readonly INotyfService _notyfService;
        private readonly IDbConnection _dbConnection;
        private readonly ImageHelper _imageHelper;

        public AppSettingController(INotyfService notyfService, IDbConnection dbConnection, ImageHelper imageHelper)
        {
            _notyfService = notyfService;
            _dbConnection = dbConnection;
            _imageHelper = imageHelper;
        }


        [NonAction]
        private async Task<EditGeneralViewModel> GetGeneralSettings()
        {
            string query = @"
                    SELECT BrandName,HeroTitle,HeroText,HeroImageUrl,AboutSubtitle,AboutText,MenuText FROM AppSettings
                ";
            var model = (await _dbConnection.QueryAsync<EditGeneralViewModel>(query)).First();
            return model;
    }
        [NonAction]
        private async Task<EditContactViewModel> GetContactSettings()
        {
            string query = @"
                    SELECT AddressText,AddressDistrict,AddressProvince,PhoneNumber,Email FROM AppSettings
                ";
            var model = (await _dbConnection.QueryAsync<EditContactViewModel>(query)).First();
            return model;
        }
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> EditGeneralSettings()
        {
            var model = await GetGeneralSettings();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditGeneralSettings(EditGeneralViewModel model)
        {
            if (ModelState.IsValid)
            {
                 if (model.HeroText == "<p><br></p>" || String.IsNullOrEmpty(model.HeroText))
                {
                    ViewBag.HeroTextErrorMessage = "Boş bırakılamaz";
                    _notyfService.Warning("Başlık metnini boş bırakmamalısınız.");
                    return View(model);
                }
                 if (model.AboutText == "<p><br></p>" || String.IsNullOrEmpty(model.AboutText))
                {
                    ViewBag.AboutTextErrorMessage = "Boş bırakılamaz";
                    _notyfService.Warning("Hakkında metnini boş bırakmamalısınız.");
                    return View(model);
                }
                if (model.HeroImageUrl != null)
                {
                    var imageModel = await _imageHelper.UploadImage(model.HeroImage, "appsettings");
                    if (!imageModel.IsSuccess)
                    {
                        ViewBag.HeroImageError = imageModel.ErrorMessage;
                        _notyfService.Error(imageModel.ErrorMessage);
                        return View(model);
                    }
                    model.HeroImageUrl = imageModel.ImageUrl;
                }
                string query = @"
                        UPDATE AppSettings
                        SET BrandName=@BrandName,HeroTitle=@HeroTitle,HeroText=@HeroText,HeroImageUrl=@HeroImageUrl,AboutSubtitle=@AboutSubtitle,AboutText=@AboutText,MenuText=@MenuText
                    ";
                await _dbConnection.ExecuteAsync(query, model);
                _notyfService.Success("Genel ayarlar başarıyla kaydedildi!");
                return View(model);
            }
            _notyfService.Error("Bir hata oluştu, ilgili alanları kontrol ediniz.");
            return View(model);
        }
        [HttpGet]
        public async Task<ActionResult> EditContactSettings()
        {
            var model = await GetContactSettings();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditContactSettings(EditContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                string query = @"
                        UPDATE AppSettings
                        SET AddressText=@AddressText,AddressDistrict=@AddressDistrict,AddressProvince=@AddressProvince,PhoneNumber=@PhoneNumber,Email=@Email
                    ";
                await _dbConnection.ExecuteAsync(query, model);
                _notyfService.Success("İletişim ayarları başarıyla kaydedildi.");
                return View(model);
            }
            _notyfService.Error("Bir hata oluştu, ilgili alanları kontrol ediniz.");
            return View(model);
        }






    }
}

Areas/Admin/Views/AppSetting/EditContactSettings.cshtml
@model EditContactViewModel
@{
    ViewData["Title"] = "İletişim Ayarları";
}

<div class="container-fluid pt-4 px-4">
    <form asp-area="Admin" asp-controller="AppSetting" asp-action="EditContactSettings" method="post"
        enctype="multipart/form-data">
        <h6 class="text-primary display-6 text-center mb-5">İletişim Ayarları</h6>
        <div class="row g-4 bg-light rounded h-100 p-4">
            <div class="col-sm-12 col-xl-6">
                <div class="mb-3">
                    <label asp-for=AddressText class="form-label"></label>
                    <input asp-for=AddressText class="form-control">
                    <span asp-validation-for=AddressText class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=AddressDistrict class="form-label"></label>
                    <input asp-for=AddressDistrict class="form-control">
                    <span asp-validation-for=AddressDistrict class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=AddressProvince class="form-label"></label>
                    <input asp-for=AddressProvince class="form-control">
                    <span asp-validation-for=AddressProvince class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 col-xl-6">
                <div class="mb-3">
                    <label asp-for=PhoneNumber class="form-label"></label>
                    <input asp-for=PhoneNumber class="form-control">
                    <span asp-validation-for=PhoneNumber class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=Email class="form-label"></label>
                    <input asp-for=Email class="form-control">
                    <span asp-validation-for=Email class="text-danger"></span>
                </div>
                
            </div>
            <div class="col-sm-12 mt-3 text-end">
                <a href="/admin/appsetting" class="btn btn-warning">Tüm Ayarlar</a>
                <button type="submit" class="btn btn-success btn-icon" title="Kaydet">
                 <i class="fas fa-save"></i>
                 </button>
            </div>
        </div>

    </form>
</div>

Areas/Admin/Views/AppSetting/EditGeneralSettings.cshtml
@model EditGeneralViewModel
@{
    ViewData["Title"] = "Genel Ayarlar";
}

<div class="container-fluid pt-4 px-4">
    <form asp-area="Admin" asp-controller="AppSetting" asp-action="EditGeneralSettings" method="post"
        enctype="multipart/form-data">
        <input type="hidden" asp-for=HeroImageUrl>
        <h6 class="text-primary display-6 text-center mb-5">Genel Ayarlar</h6>
        <div class="row g-4 bg-light rounded h-100 p-4">
            <div class="col-sm-12 col-xl-6">
                <div class="mb-3">
                    <label asp-for=BrandName class="form-label"></label>
                    <input asp-for=BrandName class="form-control">
                    <span asp-validation-for=BrandName class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=HeroTitle class="form-label"></label>
                    <input asp-for=HeroTitle class="form-control">
                    <span asp-validation-for=HeroTitle class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=AboutSubtitle class="form-label"></label>
                    <input asp-for=AboutSubtitle class="form-control">
                    <span asp-validation-for=AboutSubtitle class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=AboutText class="form-label"></label>
                    <input asp-for=AboutText class="form-control">
                    <span asp-validation-for=AboutText class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 col-xl-6">
                <div class="mb-3">
                    <label asp-for=MenuText class="form-label"></label>
                    <input asp-for=MenuText class="form-control">
                    <span asp-validation-for=MenuText class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=HeroText class="form-label"></label>
                    <input asp-for=HeroText class="form-control">
                    <span asp-validation-for=HeroText class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for=HeroImage class="form-label"></label>
                    <input class="form-control" type="file" asp-for=HeroImage id="HeroImage"
                        accept="image/png,image/jpg,image/jpeg">
                    <div class="mt-2">
                        <img src="@Model.HeroImageUrl" id="hero-image-preview" width="100" height="100" />
                    </div>
                    <span asp-validation-for=HeroImage class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 mt-3 text-end">
                <a href="/admin/appsetting" class="btn btn-warning">Tüm Ayarlar</a>
                <button type="submit" class="btn btn-success btn-icon" title="Kaydet">
        <i class="fas fa-save"></i>
                 </button>

            </div>
        </div>

    </form>
</div>
 
<link rel="stylesheet" href="~/admin/lib/summernote/summernote-bs5.min.css">
<script src="~/admin/lib/summernote/summernote-bs5.min.js"></script>
       
    <script>
        $(document).ready(function() {
  $('#AboutText').summernote();
});
    </script>
    
 
    <script>
        $("#HeroImage").on("change", function (event) {
            const selectedFiles = event.target.files;
            $("#hero-image-preview").attr("src", window.URL.createObjectURL(selectedFiles[0]));
        });
    </script>

Areas/Admin/Views/AppSetting/Index.cshtml
@{
    ViewData["Title"] = "Ayarlar Sayfası";
}

<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-center mb-4">
            <h6 class="display-6 text-primary text-center mb-0">Ayarlar</h6>
        </div>
        <div class="d-flex justify-content-center align-items-center gap-4 my-4">
            <a class="btn btn-lg btn-success" asp-area="Admin" asp-controller="AppSetting"
                asp-action="EditGeneralSettings">Genel Ayarlar</a>
                
            <a class="btn btn-lg btn-danger" asp-area="Admin" asp-controller="AppSetting"
                asp-action="EditContactSettings">İletişim Bilgileri</a>
        </div>
    </div>
</div>