Areas/Admin/Controllers/MealController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RestaurantPortfolio.Areas.Admin.Entities.Repositories;
using RestaurantPortfolio.Areas.Admin.ViewModels;
using RestaurantPortfolio.Helpers;

namespace RestaurantPortfolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MealController : Controller
    {
        private readonly INotyfService _notyfService;
        private readonly ImageHelper _imageHelper;
        private readonly CategoryRepository _categoryRepository;
        private readonly MealRepository _mealRepository;

        public MealController(INotyfService notyfService, ImageHelper imageHelper, CategoryRepository categoryRepository, MealRepository mealRepository)
        {
            _notyfService = notyfService;
            _imageHelper = imageHelper;
            _categoryRepository = categoryRepository;
            _mealRepository = mealRepository;
        }

        public async Task<ActionResult> Index(bool id)
        {
            bool isActive =id;
            ViewBag.IsActive=isActive;
            var meal=await _mealRepository.GetAllAsync(isActive);
            return View(meal);
        }
        
        [NonAction]
        private async Task<List<SelectListItem>> GenerateCategoryListAsync()
        {
            var categories=await _categoryRepository.GetAllAsync(true);
            List<SelectListItem> categoriesSelectList=[];
            foreach (var category in categories)
            {
                categoriesSelectList.Add(new SelectListItem
                {
                    Text=category.Name,
                    Value=category.Id.ToString()
                });
            }
            return categoriesSelectList;
        }
        public async Task<ActionResult> Create()
        {
            MealCreateViewModel model=new()
            {
                CategoryList=await GenerateCategoryListAsync()

            };
            return View(model);

        }
        [HttpPost]
        public async Task<ActionResult> Create(MealCreateViewModel model,IFormFile image)
        {
            
            var imageModel=await _imageHelper.UploadImage(image,"meals");
            if(!imageModel.IsSuccess)
            {
                ViewBag.ImageError=imageModel.ErrorMessage;
                _notyfService.Error("Hata oluştu ilgili alanları kontrol ediniz!");
                return View(model);

            }
            model.MealImageUrl=imageModel.ImageUrl;


             if(ModelState.IsValid)
            {
                await _mealRepository.CreateAsync(model);
                _notyfService.Success("Yeni Yemek Kaydı eklendi");
                return RedirectToAction("Index",new {Id=true});
            }
        model.CategoryList=await GenerateCategoryListAsync();
        return View(model);

        }
         public async Task<ActionResult> Update(int id)
        {
            var meal =await _mealRepository.GetByIdAsync(id);

            if(meal !=null){
            MealUpdateViewModel mealUpdateViewModel =new (){
            Id=meal.Id,
            Name=meal.Name,
            Ingredient=meal.Ingredient,
            Price=meal.Price,
            CategoryId=meal.CategoryId,
            MealImageUrl=meal.MealImageUrl,
            IsActive=meal.IsActive,
            UpdatedDate=meal.UpdatedDate.Year==1 ? null :meal.UpdatedDate,
            CategoryList=await GenerateCategoryListAsync()
            };
            return View(mealUpdateViewModel);
            }
            return RedirectToAction("Index",new {Id=true});
              
        }
        [HttpPost]
        public async Task<ActionResult> Update(MealUpdateViewModel model)
        {
            if(ModelState.IsValid)
            {
                if (model.Image != null)
                //Eski resim kullanılmayıp, yeni resim seçilmişse
                {

                    var imageModel = await _imageHelper.UploadImage(model.Image, "meals");
                    if (!imageModel.IsSuccess)
                    {
                       
                        ViewBag.ImageError = imageModel.ErrorMessage;
                        _notyfService.Error("Bir hata oluştu, ilgili alanları kontrol ediniz.");
                        return View(model);
                    }
                    model.MealImageUrl = imageModel.ImageUrl;
                }

                await _mealRepository.UpdateAsync(model);
                _notyfService.Success("Seçmiş olduğunuz yemek kaydı güncellendi");
                return RedirectToAction("Index",new {Id=true});
                
            }
            model.CategoryList=await GenerateCategoryListAsync();
            return View(model);
        }
        public async Task<ActionResult> Active(int id)
        {
            bool isActive=await _mealRepository.ActiveAsync(id);
            return RedirectToAction("Index",new{id=isActive});
        }
        public async Task<ActionResult> Delete(int id)
        {
            await _mealRepository.DeleteAsync(id);
            _notyfService.Error("Yemek Kaydı kalıcı olarak silindi");
            return RedirectToAction("Index",new {Id=true});
        }




    }
}

Areas/Admin/Controllers/SocialController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RestaurantPortfolio.Areas.Admin.Entities.Repositories;
using RestaurantPortfolio.Areas.Admin.ViewModels;

namespace RestaurantPortfolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SocialController : Controller
    {
        private readonly INotyfService _notyfService;
        private readonly SocialRepository _socialRepository;

        public SocialController(INotyfService notyfService, SocialRepository socialRepository)
        {
            _notyfService = notyfService;
            _socialRepository = socialRepository;
        }

        public async Task<ActionResult> Index(bool id)
        {
            bool isActive=id;
            ViewBag.IsActive=isActive;
            var socials =await _socialRepository.GetAllAsync(isActive);
            return View(socials);
        }
        private List<SelectListItem> GetIconList()

        {
            List<SelectListItem> iconList=[
            new SelectListItem{Text="fab fa-github"},
            new SelectListItem{Text="fab fa-twitter-x"},
            new SelectListItem{Text="fab fa-linkedin-in"},
            new SelectListItem{Text="fab fa-medium"},
            new SelectListItem{Text="fab fa-instagram"},
            new SelectListItem{Text="fab fa-pinterest"},
            new SelectListItem{Text="fab fa-youtube"},
            new SelectListItem{Text="fab fa-facebook-f"}

           ];
           return iconList;

        }
        public async Task<ActionResult> Create()
        {
           
           SocialCreateViewModel model=new()
           {
            IconList = GetIconList()
           };
            return View(model);    
        }

        [HttpPost]
        public async Task<ActionResult> Create(SocialCreateViewModel socialCreateViewModel)
        {
            if(ModelState.IsValid)
            {
                await _socialRepository.CreateAsync(socialCreateViewModel);
                _notyfService.Success("Yeni Medya eklendi");
                return RedirectToAction("Index",new {Id=true});
            }
        socialCreateViewModel.IconList=GetIconList();
        return View(socialCreateViewModel);
        }
        public async Task<ActionResult> Update(int id)
        {
            var social =await _socialRepository.GetByIdAsync(id);
            SocialUpdateViewModel socialUpdateViewModel =new (){
            Id=social.Id,
            Name=social.Name,
            Url=social.Url,
            IconList=GetIconList(),
            UpdatedDate=social.UpdatedDate.Year==1 ? null :social.UpdatedDate,
            };
            return View(socialUpdateViewModel);
            
        }
        [HttpPost]
        public async Task<ActionResult> Update(SocialUpdateViewModel socialUpdateViewModel)
        {
            if(ModelState.IsValid)
            {
                await _socialRepository.UpdateAsync(socialUpdateViewModel);
                _notyfService.Success("Seçmiş olduğunuz medya güncellendi");
                return RedirectToAction("Index",new {Id=true});
                
            }
            socialUpdateViewModel.IconList=GetIconList();
            return View(socialUpdateViewModel);
        }
         public async Task<ActionResult> Active(int id)
        {
            bool isActive=await _socialRepository.ActiveAsync(id);
            return RedirectToAction("Index",new{id=isActive});
        }
        public async Task<ActionResult> Delete(int id)
        {
            await _socialRepository.DeleteAsync(id);
            _notyfService.Error("Medyayı kalıcı olarak silindi");
            return RedirectToAction("Index",new {Id=true});
        }



    }
}

Areas/Admin/Views/Shared/_CategoryDeletePartial.cshtml
@model CategoryViewModel

<!-- Button trigger modal -->
<a class="btn btn-danger btn-round"title="Kalıcı Olarak Sil" data-bs-toggle="modal" data-bs-target="#hard-delete-modal-@Model.Id">
  <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="hard-delete-modal-@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-danger " id="exampleModalLabel">DİKKAT!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <span class="text-danger">"@Model.Name"</span> adlı kategori silinecektir.Emin misiniz?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Hayır</button>
        <a asp-area="Admin"asp-controller="Category" asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-primary">Evet</a>
      </div>
    </div>
  </div>
</div>

Areas/Admin/Views/Shared/_FooterPartial.cshtml
   <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2023 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
            </div>
</footer>

Areas/Admin/Views/Shared/_HeadPartial.cshtml
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>RestoranApp</title>

<!-- Plugins: CSS -->
<link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
<link rel="stylesheet" href="~/admin/vendors/ti-icons/css/themify-icons.css">
<link rel="stylesheet" href="~/admin/vendors/css/vendor.bundle.base.css">
<link rel="stylesheet" href="~/admin/vendors/font-awesome/css/font-awesome.min.css">

<!-- Plugin CSS for this page -->
<link rel="stylesheet" href="~/admin/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">

<!-- Layout Styles -->
<link rel="stylesheet" href="~/admin/css/style.css">

<!-- Favicon -->
<link rel="shortcut icon" href="~/admin/images/favicon.png" />

<!-- Additional Styles -->
<link href="~/admin/css/all.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="~/admin/lib/summernote/summernote-bs5.min.css">

Areas/Admin/Views/Shared/_JsPartial.cshtml
    <!-- plugins:js -->
    <script src="~/admin/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/admin/vendors/chart.js/chart.umd.js"></script>
    <script src="~/admin/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/admin/js/off-canvas.js"></script>
    <script src="~/admin/js/misc.js"></script>
    <script src="~/admin/js/settings.js"></script>
    <script src="~/admin/js/todolist.js"></script>
    <script src="~/admin/js/jquery.cookie.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/admin/js/dashboard.js"></script>
    <!-- End custom js for this page -->

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    @await Html.PartialAsync("_HeadPartial")
  </head>
  <body>
    <div class="container-scroller">
      
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
          <a class="navbar-brand brand-logo"asp-area=""asp-controller="Home" asp-action="Index" >RestoranApp<img src="~/admin/images/logo-mini.svg" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" asp-controller="Home" asp-action="Index"><img src="~/admin/images/logo-mini.svg" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
              <div class="input-group">
                <div class="input-group-prepend bg-transparent">
                  <i class="input-group-text border-0 mdi mdi-magnify"></i>
                </div>
                <input type="text" class="form-control bg-transparent border-0" placeholder="Ara">
              </div>
            </form>
          </div>
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link " id="profileDropdown" href="#" aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="~/admin/images/mervetürk.jpeg" alt="image">
                  <span class="availability-status online"></span>
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">Merve Arpacıoğlu Türk</p>
                </div>
              </a>        
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
              <a class="nav-link">
                <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
              </a>
            </li> 
              
          </ul>
          
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
         @await Html.PartialAsync("_SideBarMenuPartial")
        </nav>
        <!-- partial -->
        <div class="main-panel">
          
          @RenderBody()
          <!-- content-wrapper ends -->
       @await Html.PartialAsync("_FooterPartial")
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
  @await Html.PartialAsync("_JsPartial")
  @await Component.InvokeAsync("Notyf")
  </body>
</html>

Areas/Admin/Views/Shared/_MasterChefDeletePartial.cshtml
@model MasterChefViewModel

<!-- Button trigger modal -->
<a class="btn btn-danger btn-round"title="Kalıcı Olarak Sil" data-bs-toggle="modal" data-bs-target="#hard-delete-modal-@Model.Id">
  <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="hard-delete-modal-@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-danger " id="exampleModalLabel">DİKKAT!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <span class="text-danger">"@Model.Name"</span> adlı Şef Bilgisi silinecektir.Emin misiniz?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Hayır</button>
        <a asp-area="Admin"asp-controller="MasterChef" asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-primary">Evet</a>
      </div>
    </div>
  </div>
</div>

Areas/Admin/Views/Shared/_MealDeletePartial.cshtml
@model MealViewModel

<!-- Button trigger modal -->
<a class="btn btn-danger btn-round"title="Kalıcı Olarak Sil" data-bs-toggle="modal" data-bs-target="#hard-delete-modal-@Model.Id">
  <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="hard-delete-modal-@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-danger " id="exampleModalLabel">DİKKAT!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <span class="text-danger">"@Model.Name"</span> adlı Yemek Kaydı silinecektir.Emin misiniz?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Hayır</button>
        <a asp-area="Admin"asp-controller="Meal" asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-primary">Evet</a>
      </div>
    </div>
  </div>
</div>

Areas/Admin/Views/Shared/_ServiceDeletePartial.cshtml
@model ServiceViewModel

<!-- Button trigger modal -->
<a class="btn btn-danger btn-round"title="Kalıcı Olarak Sil" data-bs-toggle="modal" data-bs-target="#hard-delete-modal-@Model.Id">
  <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="hard-delete-modal-@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-danger " id="exampleModalLabel">DİKKAT!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <span class="text-danger">"@Model.Title"</span> adlı hizmet silinecektir.Emin misiniz?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Hayır</button>
        <a asp-area="Admin"asp-controller="Service" asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-primary">Evet</a>
      </div>
    </div>
  </div>
</div>

Areas/Admin/Views/Shared/_SideBarMenuPartial.cshtml
 <ul class="nav">
            <li class="nav-item">
              <a asp-area="Admin" asp-controller="Home"asp-action="Index" class="nav-link"aria-expanded="false" aria-controls="forms">
                <span class="menu-title">Anasayfa</span>
                <i class="mdi mdi-home-edit menu-icon"></i>
              </a>
            </li>
            <li class="nav-item nav-link">
              <a asp-area="Admin"asp-controller="Category"asp-action="Index"asp-route-id="true"class="nav-link" aria-expanded="false" aria-controls="forms">
                <span class="menu-title">Kategoriler</span>
                <i class="mdi mdi-room-service-outline menu-icon"></i>  
              </a> 
            </li>
           
            <li class="nav-item nav-link">
              <a asp-area="Admin" asp-controller="Service"asp-action="Index"asp-route-id="true" class="nav-link" aria-expanded="false" aria-controls="forms">
                <span class="menu-title">Hizmetlerimiz</span>
                <i class="mdi mdi-cards-variant menu-icon"></i>

              </a>             
            </li>   
            <li class="nav-item nav-link">
            <a asp-area="Admin" asp-controller="Social" asp-action="Index" asp-route-id="true" class ="nav-link" aria-expanded="false" aria-controls="tables">
                <span class="menu-title">Sosyal Medya</span>
                <i class="mdi mdi-folder-play menu-icon"></i>
              </a>
            </li>       
            <li class="nav-item nav-link">
              <a asp-area="Admin" asp-controller="Meal" asp-action="Index" asp-route-id="true" class="nav-link" aria-expanded="false" aria-controls="tables">
                <span class="menu-title">Yemek Menüsü</span>
                <i class="mdi mdi-silverware-fork-knife menu-icon"></i>
              </a>
            </li>              
            <li class="nav-item nav-link">
              <a asp-area="Admin" asp-controller="MasterChef" asp-action="Index" asp-route-id="true" class="nav-link" aria-expanded="false" aria-controls="icons">
                <span class="menu-title">MasterChef</span>
                <i class="mdi mdi-chef-hat menu-icon"></i>
                
              </a>
              
            </li> 
            
            <li class="nav-item nav-link">
              <a <a asp-area="Admin" asp-controller="Reservation" asp-action="Index"  class="nav-link" aria-expanded="false" aria-controls="icons">
                <span class="menu-title">Rezervasyon </span>
                <i class="mdi mdi-card-account-phone menu-icon"></i> 
              </a>
            </li>
            @* <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
                <span class="menu-title">Müşteri Yorumları</span>
                <i class="mdi mdi-comment-account-outline menu-icon"></i> 
              </a>   
            </li>     *@
             <li class="nav-item nav-link">
              <a asp-area="Admin" asp-controller="AppSetting" asp-action="Index" class="nav-link" aria-expanded="false" aria-controls="icons">
                <span class="menu-title">Ayarlar </span>
                <i class="mdi mdi-cogs menu-icon"></i>
              </a>  
            </li>           
          </ul>

Areas/Admin/Views/Shared/_SocialDeletePartial.cshtml
@model SocialViewModel

<!-- Button trigger modal -->
<a class="btn btn-danger btn-round"title="Kalıcı Olarak Sil" data-bs-toggle="modal" data-bs-target="#hard-delete-modal-@Model.Id">
  <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="hard-delete-modal-@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-danger " id="exampleModalLabel">DİKKAT!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <span class="text-danger">"@Model.Name"</span> adlı Sosyal Medya silinecektir.Emin misiniz?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Hayır</button>
        <a asp-area="Admin"asp-controller="Social" asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-primary">Evet</a>
      </div>
    </div>
  </div>
</div>