Areas/Admin/ViewModels/MasterChefViewModel.cs
using System;

namespace RestaurantPortfolio.Areas.Admin.ViewModels;

public class MasterChefViewModel
{
    public int Id {get;set;}
	public string? Name {get;set;}
	public string? ChefText {get;set;}
	public string? MasterChefsUrl {get;set;}
	public bool IsActive {get;set;}
	public DateTime? UpdatedDate {get;set;}

}

Models/MasterChef.cs
using System;

namespace RestaurantPortfolio.Models.Entities;

public class MasterChef

{
    public int Id {get;set;}
	public string? Name {get;set;}
	public string? ChefText {get;set;}
	public string? MasterChefsUrl {get;set;}
	public bool IsActive {get;set;}
	public DateTime CreatedDate {get;set;}
	public DateTime UpdatedDate {get;set;}


}

Areas/Admin/Controllers/MasterChefController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using RestaurantPortfolio.Areas.Admin.Entities.Repositories;
using RestaurantPortfolio.Helpers;
using RestaurantPortfolio.Areas.Admin.ViewModels;
using RestaurantPortfolio.Models.Entities;

namespace RestaurantPortfolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MasterChefController : Controller
    {
        
        private readonly ImageHelper _imageHelper;
        private readonly MasterChefRepository _masterChefRepository;
        private readonly INotyfService _notyfService;

        public MasterChefController(ImageHelper imageHelper, MasterChefRepository masterChefRepository, INotyfService notyfService)
        {
            _imageHelper = imageHelper;
            _masterChefRepository = masterChefRepository;
            _notyfService = notyfService;
        }

        public async Task<ActionResult> Index(bool id)
        {
            bool isActive =id;
            ViewBag.IsActive=isActive;
            var masterchef=await _masterChefRepository.GetAllAsync(isActive);
            return View(masterchef);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(MasterChefCreateViewModel model,IFormFile image)
        {
            
            var imageModel=await _imageHelper.UploadImage(image,"masterchefs");
            if(!imageModel.IsSuccess)
            {
                ViewBag.ImageError=imageModel.ErrorMessage;
                _notyfService.Error("Hata oluştu ilgili alanları kontrol ediniz!");
                return View(model);

            }
            model.MasterChefsUrl=imageModel.ImageUrl;


             if(ModelState.IsValid)
            {
                await _masterChefRepository.CreateAsync(model);
                _notyfService.Success("Yeni Şef Kaydı eklendi");
                return RedirectToAction("Index",new {Id=true});
            }
        return View(model);

        }
        public async Task<ActionResult> Update(int id)
        {
            var masterChef =await _masterChefRepository.GetByIdAsync(id);

            if(masterChef !=null){
             MasterChefUpdateViewModel masterChefUpdateViewModel =new (){
            Id=masterChef.Id,
            Name=masterChef.Name,
            ChefText=masterChef.ChefText,
            MasterChefsUrl=masterChef.MasterChefsUrl,
            UpdatedDate=masterChef.UpdatedDate.Year==1 ? null :masterChef.UpdatedDate,
            };
            return View(masterChefUpdateViewModel);
            }
            return RedirectToAction("Index",new {Id=true});
            
            
        }
        [HttpPost]
        public async Task<ActionResult> Update(MasterChefUpdateViewModel model)
        {
            if(ModelState.IsValid)
            {
                if (model.Image != null)
                //Eski resim kullanılmayıp, yeni resim seçilmişse
                {

                    var imageModel = await _imageHelper.UploadImage(model.Image, "masterchefs");
                    if (!imageModel.IsSuccess)
                    {
                       
                        ViewBag.ImageError = imageModel.ErrorMessage;
                        _notyfService.Error("Bir hata oluştu, ilgili alanları kontrol ediniz.");
                        return View(model);
                    }
                    model.MasterChefsUrl = imageModel.ImageUrl;
                }

                await _masterChefRepository.UpdateAsync(model);
                _notyfService.Success("Seçmiş olduğunuz şef güncellendi");
                return RedirectToAction("Index",new {Id=true});
                
            }
            return View(model);
        }
        public async Task<ActionResult> Active(int id)
        {
            bool isActive=await _masterChefRepository.ActiveAsync(id);
            return RedirectToAction("Index",new{id=isActive});
        }
        public async Task<ActionResult> Delete(int id)
        {
            await _masterChefRepository.DeleteAsync(id);
            _notyfService.Error("Şef kalıcı olarak silindi");
            return RedirectToAction("Index",new {Id=true});
        }


    }
}

Areas/Admin/Views/MasterChef/Create.cshtml
@model MasterChefCreateViewModel
@{
    ViewData["Title"] = "Yeni Şef Kaydı";
}
   
        <div class="container-fluid pt-4 px-4">
             <div class="bg-light rounded p-4">
             <h6 class="mb-4 display-6 fs-3 text-primary ">Yeni Şef Kaydı</h6>
                  <form asp-area="Admin"asp-controller="MasterChef"asp-action="Create" method="post" enctype="multipart/form-data">  
               
            <div class="row">
             <div class="col-12 col-xl-8">
             <div class="mb-3">
                <div class="text-danger" asp-validation-summary="All"></div>
            <label asp-for="Name" class="form-label"></label>
              <input asp-for="Name" class="form-control">   
              <span class="text-danger"asp-validation-for="Name"></span>                    
                 </div>
                  <div class="mb-3">
            
            <label asp-for="ChefText" class="form-label"></label>
              <input asp-for="ChefText" class="form-control">   
              <span class="text-danger"asp-validation-for="ChefText"></span>                    
                 </div>
              
             
            <div class="mb-3 form-check">
                <input asp-for="IsActive" class="form-check- ">
                <label class=""asp-for="IsActive"class="form-check-label"></label>
                </div>
                 <div class="mb-3">
                        <label asp-for="Image" class="form-label">Resim Yükle</label>
                        <input asp-for="Image" class="form-control" type="file" id="image" name="image"
                            accept="image/png,image/jpg,image/jpeg,image/webp">
                        <div class="mt-2">
                            <img id="image-preview" width="100" height="100" style="display: none;"
                            />
                        </div>
                        <span class="text-danger">@ViewBag.ImageError</span>
                    </div>
                </div>
                </div>   
                 <div class="d-flex justify-content-end align-items-center gap-2">
    <!-- Kaydet Butonu -->
    <button type="submit" class="btn btn-success btn-icon" title="Kaydet">
        <i class="fas fa-save"></i>
    </button>

    <!-- Vazgeç Butonu -->
    @if(ViewBag.IsActive=true)
    {
        <a asp-area="Admin" asp-controller="MasterChef" asp-action="Index" asp-route-id="true"
       class="btn btn-warning btn-icon d-flex align-items-center justify-content-center" title="Vazgeç">
        <i class="fas fa-close "></i>
    </a>   
    }
     
    
    
</div>                      
                </form>
                        </div>
                    </div>
 <script>
    document.getElementById("image").addEventListener("change", function (e) {
        const preview = document.getElementById("image-preview");
        const file = e.target.files[0];

        if (file && file.type.startsWith("image/")) {
            preview.src = URL.createObjectURL(file);
            preview.style.display = "block"; // Önizleme alanını görünür yap
        } else {
            preview.src = "";
            preview.style.display = "none"; // Geçersiz dosya durumunda önizlemeyi gizle
        }
    });
</script>

Areas/Admin/Views/MasterChef/Index.cshtml
@model IEnumerable<MasterChefViewModel>
@{
    ViewData["Title"] = "MasterChef";
}

 <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body"> 
                     <h6 class="card-title"> @(ViewBag.IsActive ?  "ŞEFLER" : "AKTİF OLMAYAN ŞEFLER SAYFASI")</h6> 
     
      @if (ViewBag.IsActive== true) 
      {
      <a asp-area="Admin" asp-controller="MasterChef" asp-action="Index" asp-route-id="false" class="btn btn-danger btn-round"title="Aktif Olmayan Şefleri göster">
      <i class="mdi mdi-chevron-double-up"></i>
      </a>

      }else
      {
      <a asp-area="Admin" asp-controller="MasterChef" asp-action="Index" asp-route-id="true" class="btn btn-success btn-round"title="Aktif Şefleri Göster">
      <i class="fas fa-check"></i>
      </a>
      }
      <a asp-area="Admin" asp-controller="MasterChef" asp-action="Create" class="btn btn-primary btn-round"title="Yeni Şef Kaydı Oluştur">
      <i class="mdi mdi-plus-circle-outline"></i>
      </a>
                    
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th> Şef Profili </th>
                          <th> Id </th>
                          <th> Şefin İsmi </th>
                          <th> Şef Bilgisi </th>
                          <th scope="col">Aktif</th>
                        <th width="120">İşlemler<th> 
                        </tr>
                      </thead>
                      <tbody>
                      @foreach (var x in Model)
{
    <tr>
        <td class="py-1">
        <img src="@x.MasterChefsUrl" alt="image" />
         </td>
        <td>@x.Id</td>
        <td>@x.Name</td>
        <td>@x.ChefText</td>
        <td> 
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" role="switch" id="isActive-@x.Id"
                    @(x.IsActive ? "checked" : "") 
                    onchange="changeIsActive(@x.Id, this.checked)">
                <label class="form-check-label" for="isActive-@x.Id"></label>
            </div>
        </td>
        <td>
            <a asp-area="Admin" asp-controller="MasterChef" asp-action="Update" asp-route-id="@x.Id" class="btn btn-warning btn-round" title="Düzelt">
                <i class="mdi mdi-pencil-outline"></i>
            </a>
            <partial name="_MasterChefDeletePartial" model="@x" />
        </td>
    </tr>
}

                      </tbody>
                    </table>
                  
                </div>
              </div>
<script>
        function changeIsActive(masterChefId){
            $.ajax({
                url: `/admin/masterChef/active/${masterChefId}`,
                type: 'GET',
                success: function(response){
                    
                    console.log(response==0 ?"İşlem başarısız": "İşlem başarılı");
                },
                error: function(error){
                    console.log(error);
                }
            });
        }
    </script>

Areas/Admin/Views/MasterChef/Update.cshtml
@model MasterChefUpdateViewModel
@{
    ViewData["Title"] = "Şef Güncelleme";
}
   
        <div class="container-fluid pt-4 px-4">
             <div class="bg-light rounded p-4">
            <h6 class="mb-4 display-6 fs-3 text-primary ">Şef Kaydı Güncelleme</h6>
                <form asp-area="Admin"asp-controller="MasterChef"asp-action="Update" method="post"enctype="multipart/form-data">
            <input type="hidden" asp-for=UpdatedDate/>
            <input type="hidden" asp-for="MasterChefsUrl">


            <div class="row">
             <div class="col-12 col-xl-8">
             <div class="mb-3">
            <div class="text-danger" asp-validation-summary="All"></div>
            <label asp-for="Name" class="form-label"></label>
              <input asp-for="Name" class="form-control">   
              <span class="text-danger"asp-validation-for="Name"></span>                    
                 </div>
              <div class="mb-3">
          
            <label asp-for="ChefText" class="form-label"></label>
              <input asp-for="ChefText" class="form-control">   
              <span class="text-danger"asp-validation-for="ChefText"></span>                    
                 </div>
              
                <div class="mb-3 form-check">
                <input asp-for="IsActive" class="form-check-input">
                <label asp-for="IsActive"class="form-check"></label>
                </div>
                 <div class="mb-3 form-group" >
                        <label asp-for="Image"class="form-label">Resim Yükle</label>
                        <input asp-for="Image" class="form-control" type="file" id="image" name="image"
                            accept="image/png,image/jpg,image/jpeg,image/webp">
                        <div class="mt-2">
                            <img src="@Model.MasterChefsUrl" id="image-preview" width="100" height="100"  />
                        </div>
                        <span class="text-danger">@ViewBag.ImageError</span>
                    </div>
                      
                <div class="form-group">
                    <span class="text-primary lead">Son Güncelleme Tarihi:</span>
                    <span class="lead">@(Model.UpdatedDate==null ? "Bu Şef Kaydı henüz güncellenmemiştir":
                        Model.UpdatedDate)</span>
                 </div>
                </div>
                </div>   
                 <div class="d-flex justify-content-end align-items-center gap-2">
    <!-- Kaydet Butonu -->
    <button type="submit" class="btn btn-success btn-icon" title="Kaydet">
        <i class="fas fa-save"></i>
    </button>

    @if(ViewBag.IsActive=true)
    {
        <a asp-area="Admin" asp-controller="MasterChef" asp-action="Index" asp-route-id="true"
       class="btn btn-warning btn-icon d-flex align-items-center justify-content-center" title="Vazgeç">
        <i class="fas fa-close "></i>
    </a>   
    }
</div>                     
                </form>
         </div>
            </div>
 <script>
    document.getElementById("image").addEventListener("change", function (e) {
        const preview = document.getElementById("image-preview");
        const file = e.target.files[0];

        if (file && file.type.startsWith("image/")) {
            preview.src = URL.createObjectURL(file);
            preview.style.display = "block"; // Önizleme alanını görünür yap
        } else {
            preview.src = "";
            preview.style.display = "none"; // Geçersiz dosya durumunda önizlemeyi gizle
        }
    });
</script>